script/vue3/1.x/gen-app-fa@bnrlike.sh
script/vue3/1.x/gen-app-fa@navypitch.sh
script/vue3/1.x/gen-display_form@bnrlike.sh
script/vue3/1.x/gen-display_form@navypitch.sh
script/vue3/1.x/gen-entry_form@bnrlike.sh
script/vue3/1.x/gen-entry_form@navypitch.sh
script/vue3/1.x/gen-fixed_table.sh
script/vue3/1.x/gen-official_form.sh
script/vue3/1.x/gen-paged_grid_drawer_dialog@bnrlike.sh
script/vue3/1.x/gen-paged_table_drawer_dialog@bnrlike.sh
script/vue3/1.x/gen-paged_table_drawer_dialog@navypitch.sh
script/vue3/1.x/gen-paged_table@bnrlike.sh
script/vue3/1.x/gen-paged_table@navypitch.sh
script/vue3/1.x/gen-tabs_excel_form@bnrlike.sh
script/vue3/1.x/gen-tabs_excel_form@navypitch.sh
script/vue3/1.x/gen-week_grid@navypitch.sh
